# Generated by Django 5.2.8 on 2025-12-12 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id_workflow', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.CharField(max_length=8, verbose_name='ID Proyecto')),
                ('nom_proyecto', models.CharField(max_length=70, verbose_name='Nombre Proyecto')),
                ('jefe_proyecto', models.CharField(max_length=15, verbose_name='Jefe de Proyecto')),
                ('desc_proyecto', models.TextField(verbose_name='Descripción Proyecto')),
                ('componente', models.CharField(max_length=30, verbose_name='Componente')),
                ('linea_base', models.CharField(blank=True, max_length=80, null=True, verbose_name='Línea Base')),
                ('release', models.CharField(blank=True, max_length=80, null=True, verbose_name='Release')),
                ('creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('qa_estimado', models.DateField(verbose_name='QA Estimado')),
                ('pap_estimado', models.DateField(verbose_name='PAP Estimado')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-creacion'],
            },
        ),
        migrations.CreateModel(
            name='PlanPruebaQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prueba', models.PositiveSmallIntegerField(verbose_name='ID Prueba')),
                ('prueba', models.CharField(max_length=80, verbose_name='Prueba')),
                ('avance', models.CharField(default='0%', max_length=4, verbose_name='Avance')),
                ('resultado', models.CharField(choices=[('No iniciado', 'No iniciado'), ('En proceso', 'En proceso'), ('Ok', 'Ok'), ('No Ok', 'No Ok')], default='No iniciado', max_length=20, verbose_name='Resultado')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_pruebas', to='workflow.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Plan de Prueba QA',
                'verbose_name_plural': 'Planes de Prueba QA',
                'ordering': ['id_prueba'],
                'unique_together': {('workflow', 'id_prueba')},
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividad', models.PositiveIntegerField(verbose_name='ID Actividad')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('usuario', models.CharField(max_length=15, verbose_name='Usuario')),
                ('estado_workflow', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Cerrado', 'Cerrado')], max_length=20, null=True, verbose_name='Estado Workflow')),
                ('proceso', models.CharField(blank=True, choices=[('linea base', 'Línea Base'), ('RM Rev', 'Revisión RM'), ('Diff Info', 'Informe Diferencias'), ('QA', 'Pruebas QA')], max_length=20, null=True, verbose_name='Proceso')),
                ('estado_proceso', models.CharField(blank=True, choices=[('No Iniciado', 'No Iniciado'), ('En Proceso', 'En Proceso'), ('Ok', 'Ok'), ('No Ok', 'No Ok')], max_length=20, null=True, verbose_name='Estado Proceso')),
                ('actividad', models.CharField(max_length=35, verbose_name='Actividad')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='workflow.workflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['-fecha'],
                'unique_together': {('workflow', 'id_actividad')},
            },
        ),
    ]
