# Generated by Django 5.2.8 on 2025-12-14 03:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='codigo_rm',
            field=models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='El código RM solo puede contener letras y números', regex='^[a-zA-Z0-9]*$')], verbose_name='Código RM'),
        ),
    ]
