# Generated by Django 5.2.8 on 2025-12-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflow_codigo_rm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflow',
            name='codigo_rm',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Código RM'),
        ),
    ]
