# Generated by Django 5.2.8 on 2025-12-14 15:46

import django.core.validators
from django.db import migrations, models


def convert_avance_to_integer(apps, schema_editor):
    """
    Convert avance field from string format ('0%', '50%', '100%') to integer (0, 50, 100)
    """
    PlanPruebaQA = apps.get_model('workflow', 'PlanPruebaQA')

    for prueba in PlanPruebaQA.objects.all():
        # Extract the numeric value from the percentage string
        # Remove '%' and convert to integer
        if prueba.avance:
            try:
                # Remove '%' character and convert to int
                avance_str = prueba.avance.replace('%', '').strip()
                avance_int = int(avance_str)
                # Ensure it's within 0-100 range
                if 0 <= avance_int <= 100:
                    prueba.avance = str(avance_int)  # Store as string temporarily
                else:
                    prueba.avance = '0'
            except (ValueError, AttributeError):
                # If conversion fails, default to 0
                prueba.avance = '0'
        else:
            prueba.avance = '0'
        prueba.save()


def convert_resultado_choices(apps, schema_editor):
    """
    Convert old resultado choices ('Ok', 'No Ok') to new choices ('Aprobado', 'No aprobado')
    """
    PlanPruebaQA = apps.get_model('workflow', 'PlanPruebaQA')

    for prueba in PlanPruebaQA.objects.all():
        if prueba.resultado == 'Ok':
            prueba.resultado = 'Aprobado'
        elif prueba.resultado == 'No Ok':
            prueba.resultado = 'No aprobado'
        # 'No iniciado' and 'En proceso' remain the same
        prueba.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_workflow_codigo_rm'),
    ]

    operations = [
        # Step 1: Convert percentage strings to plain integers (still as CharField)
        migrations.RunPython(convert_avance_to_integer, reverse_code=migrations.RunPython.noop),

        # Step 2: Change field type from CharField to PositiveSmallIntegerField
        migrations.AlterField(
            model_name='planpruebaqa',
            name='avance',
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ],
                verbose_name='Avance'
            ),
        ),

        # Step 3: Update resultado choices
        migrations.RunPython(convert_resultado_choices, reverse_code=migrations.RunPython.noop),

        # Step 4: Update resultado field with new choices
        migrations.AlterField(
            model_name='planpruebaqa',
            name='resultado',
            field=models.CharField(
                choices=[
                    ('No iniciado', 'No iniciado'),
                    ('En proceso', 'En proceso'),
                    ('Aprobado', 'Aprobado'),
                    ('No aprobado', 'No aprobado')
                ],
                default='No iniciado',
                max_length=20,
                verbose_name='Resultado'
            ),
        ),
    ]
