# Generated by Django 5.2.8 on 2025-11-21 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este username.'}, help_text='Requerido. 150 caracteres o menos. Solo letras.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='El username solo puede contener letras (a-z)', regex='^[a-zA-Z]+$')]),
        ),
    ]
